import * as model from "../../index"
describe("Payment.Card.Creatable", () => {
	it("from", async () => {
		const payment = await model.Payment.Card.Creatable.from("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjYXJkIiwiaWF0IjoxNTY5MjY1MzQ3MDk4LCJpZCI6InhMRmp6RWYzX3M0YyIsIm51bWJlciI6InRlc3QwMDEiLCJyZWZlcmVuY2UiOiJjY2ExODEyMS05YjZjLTRkYjQtODJhZS0yZjk5ZjkxNGM0YWQiLCJkZXNjcmlwdG9yIjoidGVzdCB0cmFuc2FjdGlvbiIsImlwIjoiODIuMjA5LjE0MC4xOTUiLCJjcmVhdGVkIjoiMjAxOS0wOS0yM1QxOTowMjoyNiswMDowMCIsImFtb3VudCI6MTMzNy40MiwiY3VycmVuY3kiOiJTRUsiLCJjYXJkIjp7ImlkIjoiT2l0cGl5ZE8iLCJzY2hlbWUiOiJ2aXNhIiwiaWluIjoiNDExMTExMTEiLCJsYXN0NCI6IjExMTEiLCJleHBpcmVzIjpbMSwyMF19LCJjYXB0dXJlIjpbXSwicmVmdW5kIjpbXX0.Zw-j7VnqnXehpfs7aLmhdrVBzQ2rNsRAvL7o_0Y-JmFPX-6H3MTjd_3UZBLxL9GBoTcOMIOa0OrtAFf0-kwzBzTmTBOpSs9ISjI6PupemmDz5ye9wqtNgu6XLRBSs2f-XaJ9ZhMOFPgmiko-_jhAoZ0ZM4rll9Secib5TwNfmaaVGySbSPUTHNkSc9NtZivsVQJr45SQ5Y_bhOKcjueSrj8Czp3Al7Z6jGVWwRfwgZmv_YkSumSO8yiORWzsrVBP_SyrvOwovxL0xYu9eGDAOf3xmimqCkZe9fI-dtCTvnNc_SSLaZSA4ev1BR04jnP0ruSBLqebHydDl6BBltx1xQ")
		expect(payment).toEqual({
			amount: 1337.42,
			currency: "SEK",
			reference: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjYXJkIiwiaWF0IjoxNTY5MjY1MzQ3MDk4LCJpZCI6InhMRmp6RWYzX3M0YyIsIm51bWJlciI6InRlc3QwMDEiLCJyZWZlcmVuY2UiOiJjY2ExODEyMS05YjZjLTRkYjQtODJhZS0yZjk5ZjkxNGM0YWQiLCJkZXNjcmlwdG9yIjoidGVzdCB0cmFuc2FjdGlvbiIsImlwIjoiODIuMjA5LjE0MC4xOTUiLCJjcmVhdGVkIjoiMjAxOS0wOS0yM1QxOTowMjoyNiswMDowMCIsImFtb3VudCI6MTMzNy40MiwiY3VycmVuY3kiOiJTRUsiLCJjYXJkIjp7ImlkIjoiT2l0cGl5ZE8iLCJzY2hlbWUiOiJ2aXNhIiwiaWluIjoiNDExMTExMTEiLCJsYXN0NCI6IjExMTEiLCJleHBpcmVzIjpbMSwyMF19LCJjYXB0dXJlIjpbXSwicmVmdW5kIjpbXX0.Zw-j7VnqnXehpfs7aLmhdrVBzQ2rNsRAvL7o_0Y-JmFPX-6H3MTjd_3UZBLxL9GBoTcOMIOa0OrtAFf0-kwzBzTmTBOpSs9ISjI6PupemmDz5ye9wqtNgu6XLRBSs2f-XaJ9ZhMOFPgmiko-_jhAoZ0ZM4rll9Secib5TwNfmaaVGySbSPUTHNkSc9NtZivsVQJr45SQ5Y_bhOKcjueSrj8Czp3Al7Z6jGVWwRfwgZmv_YkSumSO8yiORWzsrVBP_SyrvOwovxL0xYu9eGDAOf3xmimqCkZe9fI-dtCTvnNc_SSLaZSA4ev1BR04jnP0ruSBLqebHydDl6BBltx1xQ",
			type: "card",
		})
	})
})
